app/models.py
from flask import current_app
from flask_login import UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from werkzeug.security import generate_password_hash, check_password_hash

from . import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='role', lazy='dynamic')
    
    def __repr__(self):
        return '<Role %r>' % self.name


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    confirmed = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        raise AttributeError('Password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        db.session.commit()
        return True

    def __repr__(self):
        return '<User %r>' % self.username
        
    def __str__(self):
        return self.username

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[DataRequired()])

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy

from config import config


db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'string'
login_manager.login_view = 'auth.login'
mail = Mail()
moment = Moment()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    moment.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from datetime import datetime

from flask import abort, flash, Flask, make_response, render_template, redirect, request, session, url_for

from . import main
from .forms import NameForm
from .. import db
from ..models import User


@main.route('/')
def index():
    user = User.query.get(session.get('id'))
    if user is not None:
        flash(f'Welcome, {user}!')
    return render_template(
        'index.html', 
        title='Main',
        current_time=datetime.utcnow(),
        name=user
    )


@main.route('/user/<name>')
def user(name):
    user = User.query.filter_by(username=name).first()
    if user is None:
        return redirect(url_for('.login'))
    return render_template('user.html', title='User', name=user)

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{{ title }} - Application</title>
</head>

<body>

    {% include 'inc/__navbar.html' %}

    <div class="container">{% block content %}{% endblock %}</div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
    {{ moment.include_moment() }}
    
    <script>
        {% for message in get_flashed_messages() %}
            M.toast({html: '{{ message }}!', classes: 'rounded'})
        {% endfor %}
    </script>
</body>
</html>
        

app/templates/inc/__navbar.html
<nav class="light-blue darken-1 white-text">
    <div class="nav-wrapper">
        <div class="container">
            <a href="{{ url_for('main.index') }}" class="brand-logo">Logo</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                {% if current_user.is_authenticated %}
                    <li>Hello, {{ current_user.username | capitalize }}</li>
                    <li><a href="{{ url_for('auth.logout') }}">Sign out</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">Sign in</a></li>
                    <li><a href="{{ url_for('auth.register') }}">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
        

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% if name != None %}
        <h1>Hello, {{ name | capitalize }}!</h1>
    {% else %}
        <h1>Hello, World!</h1>
    {% endif %}
    <p class="flow-text">The local date and time is {{ moment(current_time).format('LLL') }}.</p>
    <p class="flow-text">That was {{ moment(current_time).fromNow(refresh=True) }}</p>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block content %}
    <h1>Hello, {{ name|capitalize }}!</h1>
{% endblock %}